export default function CommonMeta() {
  return (
    <>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        type="image/png"
        href="https://res.cloudinary.com/yosuam19/image/upload/v1628267061/kerja/kerja_logo_c2jylp.png"
      />
    </>
  );
}
